### ISSUE TITLE
doesn't work...

### ISSUE THREAD

**Issue by Kdigital01** [tegal1337/Backlink-Generator#2]
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/Backlink-Generator/lib/getAPI.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backlink-generator@1.0.0 start: `node index.js`
npm ERR! Exit status 1

any solution?

**Comment by fdciabdul** [comment]
what are you doing ? 

just clone and type `npm install`

**Comment by Kdigital01** [comment]
yes. i did it. 
Which os are u using for this. 
i am trying on Centos 7.
